// Generated by LiveScript 1.5.0
(function(){
  var begin, appBundlePath, start, app, end;
  begin = new Date();
  console.log("[yapps-loader] => begin => " + (begin - 0) + " (" + begin.toISOString() + ")");
  if (process.env['TIME_REQUIRE'] != null) {
    require('time-require');
    global.yapBaseappStartHook = global.yapWebappStartHook = function(err){
      return process.exit(0);
    };
  }
  global.yapContext = {
    module: module,
    __filename: __filename
  };
  appBundlePath = process.env['APP_BUNDLE_JS'];
  appBundlePath = './app/bundle';
  if (process.env['YAPPS_DUMP_LOADER_TIMESTAMPS'] !== 'true') {
    return require(appBundlePath);
  }
  start = new Date();
  app = require(appBundlePath);
  end = new Date();
  console.log("[yapps-loader] => bundle.js loading starts at " + (start - 0) + " (" + start.toISOString() + ")");
  console.log("[yapps-loader] => bundle.js loading ends   at " + (end - 0) + " (" + end.toISOString() + ")");
  console.log("[yapps-loader] => bundle.js loading takes " + (end - start) + "ms");
}).call(this);
